export const FETCH_RATES = "FETCH_RATES";
export const SET_ORIGIN_CURRENCY_TYPE = "SET_ORIGIN_CURRENCY_TYPE";
export const SET_TARGET_CURRENCY_TYPE = "SET_TARGET_CURRENCY_TYPE";
export const SET_AMOUNT = "SET_AMOUNT";
export const SWAP_CURRENCY_TYPE = "SWAP_CURRENCY_TYPE";
